# Generated by Django 6.0 on 2026-01-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_name', models.CharField()),
                ('rating', models.CharField()),
                ('review', models.TextField()),
                ('cover', models.ImageField(blank=True, null=True, upload_to='content/')),
            ],
        ),
    ]
