# Generated by Django 6.0 on 2026-01-08 08:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='rating',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AlterField(
            model_name='content',
            name='review',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(50, message='review length minimum 50 chapters')]),
        ),
    ]
